config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, only: [:index, :new, :create, :show, :destroy]

  resources :searches


  namespace :admin do
    resources :trains do
      resources :cars
    end

    resources :railway_stations do
      patch :update_station_position, on: :member
      patch :update_time, on: :member
    end

    resources :routes

    resources :tickets

    root 'resources#index', as: :root

  end

  namespace :client do
    resources :tickets

  end

  get 'welcome/index'

  root 'searches#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

  scope :sort_numbers, ->(sort) { sort ? order(:number) : order(number: :desc) }

  belongs_to :train

  validates :number, uniqueness: :true

  before_save :set_number

  private

  def set_number
    self.number = (train.cars.maximum(:number).to_i + 1)
  end
  
end

app/models/coupe_car.rb
class CoupeCar < Car

  validates :top_seats, :bottom_seats, presence: true
  
end

app/models/econome_car.rb
class EconomeCar < Car

  validates :top_seats, :bottom_seats, :side_top_seats, :side_bottom_seats, presence: true
  
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord


  scope :ordered, -> { select('railway_stations.*,
     railway_stations_routes.station_position')
     .joins(:railway_stations_routes)
     .order('railway_stations_routes.station_position').distinct }
     
  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  validates :title, presence: true

  def update_station_position(route, station_position)
    station_route = station_route(route)
    station_route.update(station_position: station_position) if station_route
  end

  def station_position_in(route)
    station_route(route).try(:station_position)
  end

  def update_time(route, arrival_time, departure_time)
    station_route = station_route(route)
    station_route.update(arrival_time: arrival_time, departure_time: departure_time) if station_route
  end

  def time_in(route, time)
    station_route(route).try(time)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end

end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord

  belongs_to :railway_station
  belongs_to :route
  
end

app/models/route.rb
class Route < ApplicationRecord

  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :name, presence: true
  
end

app/models/sedentery_car.rb
class SedenteryCar < Car

  validates :sedentery_seats, presence: true
  
end

app/models/sleep_car.rb
class SleepCar < Car

  validates :bottom_seats, presence: true
  
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  belongs_to :train
  belongs_to :user, optional: true
  belongs_to :start_station, class_name: 'RailwayStation'
  belongs_to :end_station, class_name: 'RailwayStation'

  after_create :send_buy_notification
  after_destroy :send_delete_notification


  def route_name
    "#{start_station.title} - #{end_station.title}"
  end

  private

  def send_delete_notification
    TicketsMailer.delete_ticket(self.user, self).deliver_now
  end

  def send_buy_notification
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

end

app/models/train.rb
class Train < ApplicationRecord

  belongs_to :route, optional: true
  belongs_to :current_station, class_name: 'RailwayStation', optional: true
  has_many :tickets
  has_many :cars

  validates :number, presence: true

  def sorted_cars
    self.choice ? self.cars.order(:number) :  self.cars.order(number: :desc)
  end

  def seats_by_type(car_type, seat_type)
    self.cars.where(type: car_type).sum(seat_type)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable

  has_many :tickets

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin

  layout "admin"

  protected

  def check_admin
    redirect_to root_path, alert: 'У вас нет прав на просмотр этой страницы' unless current_user.admin?
  end

end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < Admin::BaseController
  before_action :set_car, only: [ :show, :edit, :update, :destroy]
  before_action :set_train

  def index
    @cars = @train.cars
  end

  def new
    @car = Car.new
  end

  def show
    @car = Car.find(params[:id])
  end

  def create
    @car = @train.cars.new(car_params)
    if @car.save
      redirect_to admin_train_cars_path(@train)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to [:admin, @train]
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to admin_train_cars_path
  end

  protected

  def set_train
    @train = Train.find(params[:train_id])
  end

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit :type, :bottom_seats, :top_seats,
                                :side_bottom_seats, :side_top_seats,
                                :sedentery_seats, :number
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    if resource.admin?
      admin_root_path
    else
      root_path
    end
  end
end

app/controllers/client/base_controller.rb
class Client::BaseController < ApplicationController

  layout 'client'

  before_action :authenticate_user!

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    if (params[:start_station] && params[:end_station]).present?
      @search = Search.new(params[:start_station], params[:end_station])
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/cars/_car.html.slim
- @train.sorted_cars.each do |car|
  tr
    td= car.number
    td= car.type
    td= link_to t('common.show'), admin_train_car_path(@train, car)
    td= link_to t('common.edit'), edit_admin_train_car_path(@train, car)
    td
      = link_to t('common.delete'),
        admin_train_cars_path(@train, car),
        method: :delete,
        data:  { confirm: t('common.shure?') }

app/views/admin/cars/_coupe_car.html.slim
table style="width:30%"
  tr
    th= t('common.top_seats')
    th= t('common.bottom_seats')
  tr
    th
      = @car.top_seats
    th
      = @car.bottom_seats

app/views/admin/cars/_econome_car.html.slim
table style="width:30%"
  tr
    th= t('common.top_seats')
    th= t('common.bottom_seats'
    th= t('common.side_top_seats')
    th= t('common.side_bottom_seats'
  tr
    th
      = @car.top_seats
    th
      = @car.bottom_seats
    th
      = @car.side_top_seats
    th
      = @car.side_bottom_seats

app/views/admin/cars/_form.html.slim
= form_for ([:admin, @train, @car.becomes(Car)]) do |f|
  = render 'common/errors', resource: @car
  .field.select-type
    = f.label :type, t('common.car_type')
    = f.select :type, ['CoupeCar', 'EconomeCar', 'SedenteryCar', 'SleepCar'], {include_blank: 'Choose'}

  .field.display-none
    = f.label :top_seats, t('common.top_seats')
    = f.number_field :top_seats
  .field.display-none
    = f.label :bottom_seats, t('common.bottom_seats')
    = f.number_field :bottom_seats
  .field.display-none
    = f.label :side_top_seats, t('common.side_top_seats')
    = f.number_field :side_top_seats
  .field.display-none
    = f.label :side_bottom_seats, t('common.side_bottom_seats')
    = f.number_field :side_bottom_seats
  .field.display-none
    = f.label :sedentery_seats, t('common.sedentery_seats')
    = f.number_field :sedentery_seats
  .actions
    = f.submit t('.submit', action: @car.new_record? ? 'Создать' : 'Изменить')

app/views/admin/cars/_sedentery_car.html.slim
table style="width:30%"
  tr
    th= t('common.sedentery_seats')
  tr
    th
      = @car.sedentery_seats

app/views/admin/cars/_sleep_car.html.slim
table style="width:30%"
  tr
      th= t('common.bottom_seats')
  tr
    th
      = @car.bottom_seats

app/views/admin/cars/edit.html.slim
h1= t('.edit')
= render 'form'
= link_to t('common.back'), admin_train_cars_path(@train)

app/views/admin/cars/index.html.slim
h1= t('common.cars')
table
  thead
    tr
      th= t('common.number')
      th= t('common.car_type')
      th colspan="3"
  tbody
    = render 'car', resource: @cars
br
= link_to t('common.back'), admin_train_path(@train)
= link_to t('.new_car'), new_admin_train_car_path(@train)

app/views/admin/cars/new.html.slim
h1 = t('.new')
= render 'form'
= link_to t('common.back'), admin_train_cars_path

app/views/admin/cars/show.html.slim
p#notice= notice
p
  strong= t('common.car_type')
  = @car.type
= render @car.type.underscore
= link_to t('.to_train'), admin_train_cars_path(@train, @car)
= link_to t('common.back'), admin_train_cars_path(@train)

app/views/welcome/index.html.slim
p
  Перейти на: