config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, only: [:index, :new, :create, :show, :destroy]

  resources :searches


  namespace :admin do
    resources :trains do
      resources :cars
    end

    resources :railway_stations do
      patch :update_station_position, on: :member
      patch :update_time, on: :member
    end

    resources :routes

    resources :tickets

    root 'resources#index', as: :root

  end

  namespace :client do
    resources :tickets

  end

  get 'welcome/index'

  root 'searches#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

  scope :sort_numbers, ->(sort) { sort ? order(:number) : order(number: :desc) }

  belongs_to :train

  validates :number, uniqueness: :true

  before_save :set_number

  private

  def set_number
    self.number = (train.cars.maximum(:number).to_i + 1)
  end
  
end

app/models/coupe_car.rb
class CoupeCar < Car

  validates :top_seats, :bottom_seats, presence: true
  
end

app/models/econome_car.rb
class EconomeCar < Car

  validates :top_seats, :bottom_seats, :side_top_seats, :side_bottom_seats, presence: true
  
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord


  scope :ordered, -> { select('railway_stations.*,
     railway_stations_routes.station_position')
     .joins(:railway_stations_routes)
     .order('railway_stations_routes.station_position').distinct }
     
  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  validates :title, presence: true

  def update_station_position(route, station_position)
    station_route = station_route(route)
    station_route.update(station_position: station_position) if station_route
  end

  def station_position_in(route)
    station_route(route).try(:station_position)
  end

  def update_time(route, arrival_time, departure_time)
    station_route = station_route(route)
    station_route.update(arrival_time: arrival_time, departure_time: departure_time) if station_route
  end

  def time_in(route, time)
    station_route(route).try(time)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end

end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord

  belongs_to :railway_station
  belongs_to :route
  
end

app/models/route.rb
class Route < ApplicationRecord

  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :name, presence: true
  
end

app/models/sedentery_car.rb
class SedenteryCar < Car

  validates :sedentery_seats, presence: true
  
end

app/models/sleep_car.rb
class SleepCar < Car

  validates :bottom_seats, presence: true
  
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  belongs_to :train
  belongs_to :user, optional: true
  belongs_to :start_station, class_name: 'RailwayStation'
  belongs_to :end_station, class_name: 'RailwayStation'

  after_create :send_buy_notification
  after_destroy :send_delete_notification


  def route_name
    "#{start_station.title} - #{end_station.title}"
  end

  private

  def send_delete_notification
    TicketsMailer.delete_ticket(self.user, self).deliver_now
  end

  def send_buy_notification
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

end

app/models/train.rb
class Train < ApplicationRecord

  belongs_to :route, optional: true
  belongs_to :current_station, class_name: 'RailwayStation', optional: true
  has_many :tickets
  has_many :cars

  validates :number, presence: true

  def sorted_cars
    self.choice ? self.cars.order(:number) :  self.cars.order(number: :desc)
  end

  def seats_by_type(car_type, seat_type)
    self.cars.where(type: car_type).sum(seat_type)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable

  has_many :tickets

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin

  layout "admin"

  protected

  def check_admin
    redirect_to root_path, alert: 'У вас нет прав на просмотр этой страницы' unless current_user.admin?
  end

end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < Admin::BaseController
  before_action :set_car, only: [ :show, :edit, :update, :destroy]
  before_action :set_train

  def index
    @cars = @train.cars
  end

  def new
    @car = Car.new
  end

  def show
    @car = Car.find(params[:id])
  end

  def create
    @car = @train.cars.new(car_params)
    if @car.save
      redirect_to admin_train_cars_path(@train)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to [:admin, @train]
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to admin_train_cars_path
  end

  protected

  def set_train
    @train = Train.find(params[:train_id])
  end

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit :type, :bottom_seats, :top_seats,
                                :side_bottom_seats, :side_top_seats,
                                :sedentery_seats, :number
  end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController <Admin::BaseController

  before_action :set_ticket, only: [ :show, :edit, :update, :destroy ]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to admin_tickets_path, notice: 'Операция покупки прошла успешна'
    else
      render :edit
    end
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to  admin_tickets_path, notice: 'Изменения успешно обнавились'
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to admin_tickets_path, notice: 'Ваш билет был успешно анулирован'
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit :start_station_id, :end_station_id, :user_id,
                                   :first_name, :last_name, :passport, :train_id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    if resource.admin?
      admin_root_path
    else
      root_path
    end
  end
end

app/controllers/client/tickets_controller.rb
class Client::TicketsController < Client::BaseController

  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :destroy]

  def index
    @tickets = current_user.tickets
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)

    if @ticket.save
      redirect_to client_tickets_path, notice: 'Операция покупки прошла успешна'
    else
      redirect_to client_search_path
    end
  end

  def destroy
    @ticket.destroy
    redirect_to client_tickets_path, notice: 'Ваш билет был успешно анулирован'
  end

  private

  def set_ticket
    @ticket = current_user.tickets.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit :start_station_id, :end_station_id,
                                   :first_name, :last_name, :passport, :train_id
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    if (params[:start_station] && params[:end_station]).present?
      @search = Search.new(params[:start_station], params[:end_station])
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/tickets/_form.html.slim
= form_for([:admin, @ticket]) do |f|
  = render 'common/errors', resource: @ticket
  .field
    = f.label :user, t('.user')
    = f.collection_select :user_id, User.all, :id, :email
  .field
    = f.label :start_station, t('common.start_station')
    = f.collection_select :start_station_id, RailwayStation.all, :id, :title
  .field
    = f.label :end_station, t('common.end_station')
    = f.collection_select :end_station_id, RailwayStation.all, :id, :title
  .field
    = f.label :train, t('common.train')
    = f.collection_select :train_id, Train.all, :id, :number
  .field
    = f.label :first_name, t('.name')
    = f.text_field :first_name
  .field
    = f.label :last_name, t('.surname')
    = f.text_field :last_name
  .field
    = f.label :passport, t('.passport')
    = f.text_field :passport
  .actions
    = f.submit t('.submit', action: @ticket.new_record? ? 'Создать' : 'Изменить')

app/views/admin/tickets/_ticket.html.slim
tr
  td
    = ticket.start_station.title
    | - #{ticket.end_station.title}
  td= link_to t('common.show'),[:admin, ticket]
  td= link_to t('common.edit'), edit_admin_ticket_path(ticket)
  td
    = link_to t('common.delete'),
      [:admin, ticket],
      method: :delete,
      data:  { confirm: 'Вы уверены?' }

app/views/admin/tickets/edit.html.slim
h1= t('.edit')
= render 'form'
= link_to t('common.show'), admin_ticket_path(@ticket)
= link_to t('common.back'), admin_tickets_path

app/views/admin/tickets/index.html.slim
h1= t('.bought_tickets')
table class="table"
  thead
    tr
      th= t('common.route')
      th colspan="3"
  tbody
    = render @tickets
br
= link_to t('.new_ticket'), new_admin_ticket_path

app/views/admin/tickets/new.html.slim
h1= t('.new')
= render 'form'
= link_to t('common.back'), admin_tickets_path

app/views/admin/tickets/show.html.slim
p
  strong= t('common.route')
  = @ticket.start_station.title
  | - #{@ticket.end_station.title}
p
  strong= t('.user')
  = @ticket.user.email
p
  strong= t('.name_byer')
  = @ticket.first_name
  | - #{@ticket.last_name }

= link_to t('common.edit'), edit_admin_ticket_path(@ticket)
= link_to t('common.back'), admin_tickets_path